pushpasis/frr

cmgd/cmgd_vty.c
lib/vty.c
lib/vty.h

since there is a commit command that exist already
have named this command as commit-apply.
Signed-off-by: Abhinay Ramesh <rabhinay@vmware.com>

cmgd: changes to support commit command

---

cmgd/cmgd_vty.c
lib/cmgd_frntnd_client.c
lib/cmgd_frntnd_client.h
lib/vty.c
lib/vty.h

cmgd: GET-DATA request handle and show

---

cmgd/cmgd_frntnd_adapter.c
lib/cmgd.proto
lib/cmgd_bcknd_client.c

Code changes are done to create transactions and batches
in backnd client lib code.
Signed-off-by: Abhinay Ramesh <rabhinay@vmware.com>

cmgd: changes to support backend client msg processing

---

cmgd/cmgd_db.c
cmgd/cmgd_trxn.c

cmgd: Set the value of the leaf nodes in the GET-DATA requests

---

lib/vty.c

Code changes are done to block the vtysh until response
is received from backend. This ensures that error messages
are returned to user in the same execution flow.
Signed-off-by: Abhinay Ramesh <rabhinay@vmware.com>

lib: Changes to block vtysh until backend responds

---

cmgd/cmgd_db.c

cmgd: Add support for the cmgd_db_merge_dbs func

---

cmgd/cmgd_db.c

cmgd: BUG Fix in cmgd_db_merge_dbs

---

cmgd/cmgd_db.c

cmgd: GET-DATA request handled for leaf nodes

---

cmgd/cmgd_vty.c
lib/northbound.c

cmgd: delete-config command

---

cmgd/cmgd_db.c
cmgd/cmgd_db.h
cmgd/cmgd_vty.c
cmgd/cmgd_vty.h

cmgd: Dump the cmgd data tree in a file in JSON or XML format

---

cmgd/cmgd_db.c
cmgd/cmgd_db.h
cmgd/cmgd_vty.c

cmgd: Dump tree into file

---

cmgd/cmgd_db.c

cmgd: Dump the running tree at the time of merge

---

cmgd/cmgd_db.c
cmgd/cmgd_db.h
cmgd/cmgd_vty.c

Sigend-off-by: Yash Ranjan <ranjany@vmware.com>

cmgd: load config command

---

cmgd/cmgd_db.c

1. To crawl the whole tree, first get the fist top-level sibling and
then call the crawl function for all the siblings.
2. In the crawl function cmgd_walk_db_nodes(), instead of using
lyd_find_xpath() to get all the children, use lyd_child() function.

cmgd: Fix the tree iteration code

---

cmgd/cmgd_bcknd_adapter.c
cmgd/cmgd_bcknd_adapter.h
cmgd/cmgd_db.c
cmgd/cmgd_trxn.c
lib/northbound.c
lib/northbound.h

cmgd: Sync the backend daemons with the running DB at startup

---

cmgd/cmgd_vty.c

cmgd: Add debug commands to activate the debugs

---

tests/topotests/lib/common_config.py
tests/topotests/lib/topogen.py
tests/topotests/lib/topotest.py

This PR contains starting mgmtd daemon along with Zebra.
Signed-off-by: nguggarigoud <nguggarigoud@vmware.com>

tests: adding mgmtd support to topotests.

---

mgmtd/mgmt_bcknd_adapter.c
mgmtd/mgmt_db.c
mgmtd/mgmt_trxn.c

mgmt: fixed some memleaks and typos.

---

lib/mgmt_bcknd_client.c
lib/northbound.c
lib/northbound.h
lib/northbound_confd.c
lib/northbound_grpc.cpp
lib/northbound_sysrepo.c
mgmtd/mgmt_trxn.c

Signed-off-by: Yash Ranjan <ranajan@vmware.com>

mgmt: Fix mgmt reboot crash

---

lib/mgmt_bcknd_client.c
lib/mgmt_frntnd_client.c
mgmtd/mgmt_bcknd_adapter.c
mgmtd/mgmt_bcknd_server.c
mgmtd/mgmt_frntnd_adapter.c
mgmtd/mgmt_frntnd_server.c
mgmtd/mgmt_trxn.c

Need to pass the reference to the thread as part of thread
functions.
Signed-off-by: Abhinay Ramesh <rabhinay@vmware.com>

mgmt: changes to handle thread reference.
